###########################################################################
### Installation Tasks                                                  ###
###########################################################################

- name: Ensure Users and Groups
  ansible.builtin.include_tasks: install/users-and-groups.yml

- name: Ensure Folders
  ansible.builtin.include_tasks: install/folders.yml

- name: Check if Kafka Binary Exists
  ansible.builtin.stat:
    path: "{{ kafka_folder_binaries }}/kafka_{{ kafka_scala_version }}-{{ kafka_version }}/bin/kafka-server-start.sh"
  register: kafka_binary

- name: Download and Untar Kafka Binaries
  ansible.builtin.include_tasks: install/download-and-untar-binaries.yml
  when: not kafka_binary.stat.exists
